<?php 
if(substr($_SERVER["REQUEST_URI"], -10) == "config.php"){header("Location:./");}; 
$data['mikhmon'] = array ('1'=>'mikhmon<|<boss','mikhmon>|>jJKdoaqTpmJmaWRT');

$data['RITAZ'] = array ('1'=>'RITAZ!4913047ac445.sn.mynetname.net:50','RITAZ@|@admin','RITAZ#|#gpKfmZ1jbGJlWQ==','RITAZ%RITAZ','RITAZ^speed.net','RITAZ&AED','RITAZ*10','RITAZ(1','RITAZ)','RITAZ=10','RITAZ@!@disable');

$data['ARMAN'] = array ('1'=>'ARMAN!hfb09fte878.sn.mynetname.net:8001','ARMAN@|@admin','ARMAN#|#gpKfmZ1jbGJlWQ==','ARMAN%M5 SMS WiFi','ARMAN^login.net','ARMAN&AED','ARMAN*10','ARMAN(1','ARMAN)','ARMAN=10','ARMAN@!@disable');
$data['SMARTMARKET'] = array ('1'=>'SMARTMARKET!fad10fafd42b.sn.mynetname.net:50','SMARTMARKET@|@admin','SMARTMARKET#|#gpKfmZ1jbGJlWQ==','SMARTMARKET%SMART MARKET','SMARTMARKET^login.net','SMARTMARKET&AED','SMARTMARKET*10','SMARTMARKET(1','SMARTMARKET)','SMARTMARKET=10','SMARTMARKET@!@disable');
$data['Expo'] = array ('1'=>'Expo!f0380e7e285e.sn.mynetname.net:50','Expo@|@admin','Expo#|#gpKfmZ1jbGJlWQ==','Expo%M11 SAIF EXPO','Expo^login.net','Expo&AED','Expo*10','Expo(1','Expo)','Expo=10','Expo@!@disable');
$data['ARMAN'] = array ('1'=>'ARMAN!hfb09fte878.sn.mynetname.net:50','ARMAN@|@admin','ARMAN#|#gpKfmZ1jbGJlWQ==','ARMAN%SMS NET','ARMAN^login.net','ARMAN&AED','ARMAN*10','ARMAN(1','ARMAN)','ARMAN=10','ARMAN@!@disable');
$data['Tikka'] = array ('1'=>'Tikka!hey099eykzx.sn.mynetname.net:50','Tikka@|@admin','Tikka#|#gpKfmZ1jbGJlWQ==','Tikka%TIKKA TO NIGHT','Tikka^login.net','Tikka&AED','Tikka*10','Tikka(1','Tikka)','Tikka=10','Tikka@!@disable');
$data['SANMAR'] = array ('1'=>'SANMAR!e3220d3e89f1.sn.mynetname.net:50','SANMAR@|@admin','SANMAR#|#gpKfmZ1jbGJlWQ==','SANMAR%SMART NET','SANMAR^login.net','SANMAR&AED','SANMAR*10','SANMAR(1','SANMAR)','SANMAR=10','SANMAR@!@disable');
$data['SMARTWIFIC'] = array ('1'=>'SMARTWIFIC!d4440c542d1d.sn.mynetname.net:50','SMARTWIFIC@|@admin','SMARTWIFIC#|#gpKfmZ1jbGJlWQ==','SMARTWIFIC%M37 OMAR IRANI','SMARTWIFIC^login.net','SMARTWIFIC&AED','SMARTWIFIC*10','SMARTWIFIC(1','SMARTWIFIC)','SMARTWIFIC=10','SMARTWIFIC@!@disable');
$data['Babul'] = array ('1'=>'Babul!ce9a0c0e424d.sn.mynetname.net:50','Babul@|@admin','Babul#|#gpKfmZ1jbGJlWQ==','Babul%GEO NET','Babul^login.net','Babul&AED','Babul*10','Babul(1','Babul)','Babul=10','Babul@!@disable');
$data['GOOD'] = array ('1'=>'GOOD!b8f30b3b15a3.sn.mynetname.net:50','GOOD@|@admin','GOOD#|#gpKfmZ1jbGJlWQ==','GOOD%GOOD LUCK','GOOD^login.net','GOOD&AED','GOOD*10','GOOD(1','GOOD)','GOOD=10','GOOD@!@disable');
$data['Motijhel'] = array ('1'=>'Motijhel!e3200f7d87d0.sn.mynetname.net:50','Motijhel@|@admin','Motijhel#|#gpKfmZ1jbGJlWQ==','Motijhel%MOTIJHEL','Motijhel^login.net','Motijhel&AED','Motijhel*10','Motijhel(1','Motijhel)','Motijhel=10','Motijhel@!@disable');
$data['Jaforcamp'] = array ('1'=>'Jaforcamp!f0380fcdd15e.sn.mynetname.net:5','Jaforcamp@|@m5saif','Jaforcamp#|#q5KbnmJkaw==','Jaforcamp%jafor','Jaforcamp^login.net','Jaforcamp&AED','Jaforcamp*10','Jaforcamp(1','Jaforcamp)','Jaforcamp=10','Jaforcamp@!@disable');
$data['Japor'] = array ('1'=>'Japor!hf50978r78a.sn.mynetname.net:50','Japor@|@admin','Japor#|#gpKfmZ1jbGJlWQ==','Japor%KGF','Japor^login.net','Japor&AED','Japor*10','Japor(1','Japor)','Japor=10','Japor@!@disable');
$data['UMAR'] = array ('1'=>'UMAR!d4440c2f0ddb.sn.mynetname.net:50','UMAR@|@admin','UMAR#|#gpKfmZ1jbGJlWQ==','UMAR%TAXI NET','UMAR^login.net','UMAR&AED','UMAR*10','UMAR(1','UMAR)','UMAR=10','UMAR@!@disable');
$data['REDKASHMIRI'] = array ('1'=>'REDKASHMIRI!79ae069c39f1.sn.mynetname.net:50','REDKASHMIRI@|@admin','REDKASHMIRI#|#gpKfmZ1jbGJlWQ==','REDKASHMIRI%RED KASHMIRI','REDKASHMIRI^login.net','REDKASHMIRI&AED','REDKASHMIRI*10','REDKASHMIRI(1','REDKASHMIRI)','REDKASHMIRI=10','REDKASHMIRI@!@disable');
$data['PAKRAVI'] = array ('1'=>'PAKRAVI!742e0758672d.sn.mynetname.net:50','PAKRAVI@|@admin','PAKRAVI#|#gpKfmZ1jbGJlWQ==','PAKRAVI%PAK RAVI','PAKRAVI^login.net','PAKRAVI&AED','PAKRAVI*10','PAKRAVI(1','PAKRAVI)','PAKRAVI=10','PAKRAVI@!@disable');
$data['M33'] = array ('1'=>'M33!ce9a0c6b1272.sn.mynetname.net:50','M33@|@jamalapi','M33#|#jJKdrWlncVI=','M33%SPEED NET M33','M33^login.net','M33&AED','M33*10','M33(1','M33)','M33=10','M33@!@disable');
$data['ARMANNEW'] = array ('1'=>'ARMANNEW!f0380fdad71f.sn.mynetname.net:50','ARMANNEW@|@admin','ARMANNEW#|#gpKfmZ1jbGJlWQ==','ARMANNEW%M5 SMS WiFi','ARMANNEW^login.net','ARMANNEW&AED','ARMANNEW*10','ARMANNEW(1','ARMANNEW)','ARMANNEW=10','ARMANNEW@!@disable');
$data['LAL'] = array ('1'=>'LAL!b8f30b16e65a.sn.mynetname.net:50','LAL@|@admin','LAL#|#gpKfmZ1jbGJlWQ==','LAL%LAL MARKET','LAL^login.net','LAL&AED','LAL*10','LAL(1','LAL)','LAL=10','LAL@!@disable');
$data['Saim'] = array ('1'=>'Saim!heq09etfsts.sn.mynetname.net:50','Saim@|@admin','Saim#|#gpKfmZ1jbGJlWQ==','Saim%Dubai Net','Saim^login.net','Saim&AED','Saim*10','Saim(1','Saim)','Saim=10','Saim@!@disable');
$data['Mabarak'] = array ('1'=>'Mabarak!f0380fcdd15e.sn.mynetname.net:50','Mabarak@|@admin','Mabarak#|#gpKfmZ1jbGJlWQ==','Mabarak%MABARAK AL NOOR','Mabarak^login.net','Mabarak&AED','Mabarak*10','Mabarak(1','Mabarak)','Mabarak=10','Mabarak@!@disable');
$data['MangoNet'] = array ('1'=>'MangoNet!server48.onlinemikrotik.com:8288','MangoNet@|@alamgir','MangoNet#|#eZOVnHFma2Nj','MangoNet%Mango Net','MangoNet^login.net','MangoNet&AED','MangoNet*10','MangoNet(1','MangoNet)','MangoNet=10','MangoNet@!@disable');
$data['ALBOSHIA'] = array ('1'=>'ALBOSHIA!he308xnk99f.sn.mynetname.net','ALBOSHIA@|@alamgir','ALBOSHIA#|#eZOVnHFma2Nj','ALBOSHIA%AL BOSHIA','ALBOSHIA^login.net','ALBOSHIA&AED','ALBOSHIA*10','ALBOSHIA(1','ALBOSHIA)','ALBOSHIA=10','ALBOSHIA@!@disable');
$data['MangoNet'] = array ('1'=>'MangoNet!server48.onlinemikrotik.com:8727','MangoNet@|@alamgir','MangoNet#|#eZOVnHFma2Nj','MangoNet%MANGO NET','MangoNet^login.net','MangoNet&AED','MangoNet*10','MangoNet(1','MangoNet)','MangoNet=10','MangoNet@!@disable');
$data['OSMANM39'] = array ('1'=>'OSMANM39!d4440d8fe7e8.sn.mynetname.net:50','OSMANM39@|@admin','OSMANM39#|#gpKfmZ1jbGJlWQ==','OSMANM39%M40','OSMANM39^login.net','OSMANM39&AED','OSMANM39*10','OSMANM39(1','OSMANM39)','OSMANM39=10','OSMANM39@!@disable');
$data['IMRAN-M36'] = array ('1'=>'IMRAN-M36!d8550f596fa3.sn.mynetname.net:50','IMRAN-M36@|@admin','IMRAN-M36#|#gpKfmZ1jbGJlWQ==','IMRAN-M36%GOOD CAMP M36','IMRAN-M36^login.net','IMRAN-M36&AED','IMRAN-M36*10','IMRAN-M36(1','IMRAN-M36)','IMRAN-M36=10','IMRAN-M36@!@disable');
$data['IMRANM40'] = array ('1'=>'IMRANM40!4913047ac445.sn.mynetname.net:5002','IMRANM40@|@admin','IMRANM40#|#gpKfmZ1jbGJlWQ==','IMRANM40%KM MARKET M40','IMRANM40^uae.net','IMRANM40&AED','IMRANM40*10','IMRANM40(1','IMRANM40)','IMRANM40=10','IMRANM40@!@disable');
$data['osmanm35'] = array ('1'=>'osmanm35!d43e0c09bdb7.sn.mynetname.net:50','osmanm35@|@admin','osmanm35#|#gpKfmZ1jbGJlWQ==','osmanm35%M35','osmanm35^login.net','osmanm35&AED','osmanm35*10','osmanm35(1','osmanm35)','osmanm35=10','osmanm35@!@disable');
$data['Mohammed-M10'] = array ('1'=>'Mohammed-M10!708d0891f96a.sn.mynetname.net:50','Mohammed-M10@|@admin','Mohammed-M10#|#gpKfmZ1jbGJlWQ==','Mohammed-M10%M10-REAL STATE','Mohammed-M10^login.net','Mohammed-M10&AED','Mohammed-M10*10','Mohammed-M10(1','Mohammed-M10)','Mohammed-M10=10','Mohammed-M10@!@disable');
$data['Mohameed-M38'] = array ('1'=>'Mohameed-M38!hew09dskaxt.sn.mynetname.net:50','Mohameed-M38@|@admin','Mohameed-M38#|#gpKfmZ1jbGJlWQ==','Mohameed-M38%REAL STATE -M38','Mohameed-M38^login.net','Mohameed-M38&AED','Mohameed-M38*10','Mohameed-M38(1','Mohameed-M38)','Mohameed-M38=10','Mohameed-M38@!@disable');
$data['Mohammed-M11'] = array ('1'=>'Mohammed-M11!d43e0c09bdb7.sn.mynetname.net:50','Mohammed-M11@|@admin','Mohammed-M11#|#gpKfmZ1jbGJlWQ==','Mohammed-M11%M11 REAL State','Mohammed-M11^login.net','Mohammed-M11&AED','Mohammed-M11*10','Mohammed-M11(1','Mohammed-M11)','Mohammed-M11=10','Mohammed-M11@!@disable');
$data['Sohel-M20'] = array ('1'=>'Sohel-M20!d43e0c378f4d.sn.mynetname.net:50','Sohel-M20@|@admin','Sohel-M20#|#gpKfmZ1jbGJlWQ==','Sohel-M20%M20','Sohel-M20^login.net','Sohel-M20&AED','Sohel-M20*10','Sohel-M20(1','Sohel-M20)','Sohel-M20=10','Sohel-M20@!@disable');
$data['Fausal-Al-Ain-03'] = array ('1'=>'Fausal-Al-Ain-03!ce9e0c030cf0.sn.mynetname.net:50','Fausal-Al-Ain-03@|@admin','Fausal-Al-Ain-03#|#gpKfmZ1jbGJlWQ==','Fausal-Al-Ain-03%Madina Macksalla','Fausal-Al-Ain-03^login.net','Fausal-Al-Ain-03&AED','Fausal-Al-Ain-03*10','Fausal-Al-Ain-03(1','Fausal-Al-Ain-03)','Fausal-Al-Ain-03=10','Fausal-Al-Ain-03@!@disable');
$data['Radission'] = array ('1'=>'Radission!163.47.86.94:50','Radission@|@admin','Radission#|#ipWlpmpqbWdT','Radission%RDSN','Radission^rdsnwifi.com','Radission&BDT','Radission*10','Radission(1','Radission)','Radission=10','Radission@!@disable');
$data['BWH'] = array ('1'=>'BWH!103.243.82.58:50','BWH@|@Jamal','BWH#|#fpKmrWJmaWRT','BWH%bwhwifi.com','BWH^login.net','BWH&AED','BWH*10','BWH(1','BWH)','BWH=10','BWH@!@disable');
$data['USMAN-M33'] = array ('1'=>'USMAN-M33!hf60951kbvp.sn.mynetname.net:50','USMAN-M33@|@jamalapi','USMAN-M33#|#jJKdrWlncVI=','USMAN-M33%USMAN-M33','USMAN-M33^login.net','USMAN-M33&AED','USMAN-M33*10','USMAN-M33(1','USMAN-M33)','USMAN-M33=10','USMAN-M33@!@disable');
$data['Faisal-Mubarak'] = array ('1'=>'Faisal-Mubarak!67550573c870.sn.mynetname.net:50','Faisal-Mubarak@|@admin','Faisal-Mubarak#|#gpKfmZ1jbGJlWQ==','Faisal-Mubarak%Mubarak 11','Faisal-Mubarak^login.net','Faisal-Mubarak&AED','Faisal-Mubarak*10','Faisal-Mubarak(1','Faisal-Mubarak)','Faisal-Mubarak=10','Faisal-Mubarak@!@disable');
$data['Test'] = array ('1'=>'Test!172.16.59.232:50','Test@|@admin','Test#|#gpKfmZ1jbGJlWQ==','Test%BWH-2','Test^login.net','Test&Rp','Test*10','Test(1','Test)','Test=10','Test@!@disable');

$data['Salauddin-M2'] = array ('1'=>'Salauddin-M2!9bd8095c92cd.sn.mynetname.net:50','Salauddin-M2@|@admin','Salauddin-M2#|#gpKfmZ1jbGJlWQ==','Salauddin-M2%M2','Salauddin-M2^login.net','Salauddin-M2&AED','Salauddin-M2*10','Salauddin-M2(1','Salauddin-M2)','Salauddin-M2=10','Salauddin-M2@!@disable');